region               = "us-east-1"
api_name             = "my-api-gateway"
stage_name           = "prod"
description          = "My API Gateway for invoking Lambda functions"
endpoint_type        = "REGIONAL"
lambda_function_arn  = "arn:aws:lambda:us-east-1:123456789012:function:my-lambda-function"
